// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwBTbKKxBeY-Z1aQEDe3PsO4fCGYFIIk',
    appId: '1:936593969280:web:7f824389898ecef41fd665',
    messagingSenderId: '936593969280',
    projectId: 'login-bloc-8b15d',
    authDomain: 'login-bloc-8b15d.firebaseapp.com',
    storageBucket: 'login-bloc-8b15d.appspot.com',
    measurementId: 'G-7J941B0KK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJs7RjPBfH2zrY71nUxj6zNmEBSzRu5K0',
    appId: '1:936593969280:android:3ba581e968ab30fd1fd665',
    messagingSenderId: '936593969280',
    projectId: 'login-bloc-8b15d',
    storageBucket: 'login-bloc-8b15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBliB_LSeu-cHb62mU4MrAUjoTGH1L9Qpc',
    appId: '1:936593969280:ios:913b9b6b3c587e391fd665',
    messagingSenderId: '936593969280',
    projectId: 'login-bloc-8b15d',
    storageBucket: 'login-bloc-8b15d.appspot.com',
    iosClientId: '936593969280-2nqh7eqh24s8baoh3ag24jpjhn02cnj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolcFirebaseLoginApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBliB_LSeu-cHb62mU4MrAUjoTGH1L9Qpc',
    appId: '1:936593969280:ios:afaf39476a04e7401fd665',
    messagingSenderId: '936593969280',
    projectId: 'login-bloc-8b15d',
    storageBucket: 'login-bloc-8b15d.appspot.com',
    iosClientId: '936593969280-cr4i6s0kmh5k9k43cehftdal2gtlgang.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolcFirebaseLoginApk.RunnerTests',
  );
}
